export const VOICE_TRAINING_PROMPTS = [
  'I packed a box for our move and checked that every bright red label was easy to read.',
  'After work, I took the dog for a quick walk through the quiet park near our house.',
  'I thought the weather would improve, so we planned to meet there around three.',
  'She chose a fresh salad and shared some chips with the children at lunch.',
  'George adjusted his jacket and placed the orange badge beside his name.',
  'I had a vision for the beige living room, with casual furniture and warm light.',
  'Laura rarely takes the rural railroad, but she likes the long ride through the valley.',
  'Please bring blue glass, green cloth, crisp bread, and twelve small silver spoons.',
  'We watched the scratched clocks, washed dishes, played games, and needed rest.',
  'The cats, dogs, horses, judges, and foxes waited quietly beside their owners.',
  'We are rebuilding the office, reorganizing the shelves, and reconsidering the unfinished plan.',
  'A disagreement or misinterpretation can cause unhelpfulness and overconfidence during a conversation.',
  'I cannot believe they would not have finished because they were not ready.',
  'A boy found a coin near a loud brown owl while rain fell around the house.',
  'Kate sees green leaves, red berries, black branches, and soft white snow.',
  'A curious musician tuned the new flute before playing a beautiful evening melody.',
  'Fresh coffee, warm muffins, sliced apples, and creamy yogurt make a pleasant breakfast.',
  'Please open GitHub, search for accessibility tools, and read the selected text aloud.',
  'Scroll down slowly, zoom in twice, copy this paragraph, and return to the previous page.',
  'Set a focus timer for twenty-five minutes, then add blueberries to my shopping list.',
  'At three thirty-seven, send eight short messages to Alex, Jordan, Priya, and Zoe.',
  'I heard someone whisper that a group of whales was swimming through the cold northern water.',
  'A strong spring breeze swept scraps of paper across the street near the old brick crossing.',
  'Zero, one, two, three, four, five, six, seven, eight, nine, ten, hundred, thousand.',
  'Keep listening while I talk, and show the words you think I am saying on the screen.',
  'Let me choose which microphone to use, and remember that setting when I open the app again.',
  'Please do not change my audio output unless you ask me first and I agree.',
  'Open the app quietly in the background without taking focus or moving my cursor.',
  'Minimize this window, but keep the microphone running until I turn always listening off.',
  'Show a moving sound wave whenever the microphone is active so I know it can hear me.',
  'Use more natural training sentences because I may stumble, pause, or read one word incorrectly.',
  'Compare the words I actually said with the sentence on the screen before saving the recording.',
  'Switch to eye tracking mode and help me calibrate each point without leaving the visible box.',
  'Make the cursor ring white and easy to see against both bright and dark backgrounds.',
  'My left eye wink should make a left click, and my right eye wink should make a right click.',
  'Train the eye model carefully with my open eyes, closed eyes, and each wink separately.',
  'Search my files for the latest report, open it, and read the first paragraph aloud.',
  'Start a twenty minute timer, add milk to my list, and remind me when the timer finishes.',
  'I said the wrong word in that recording, so let me correct the transcript before it is saved.',
  'What did you hear me say, and which action did you understand from those words?',
] as const;
